version: '3'

services:
  php:
    container_name: php.demox
    build:
      context: ./
      dockerfile: ./.php.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./demox:/var/www/html/demox
    environment:
      DATABASE_URL: db
      MYSQL_USER: demox_user
      MYSQL_PASSWORD: demox-p4sswd
      MYSQL_DATABASE: demox_db
    links:
      - db

  db:
    image: mysql:8.0
    container_name: dtb.demox
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/dbcreation.sql:/tmp/dbcreation.sql
      - ./db/dbimport.sh:/tmp/dbimport.sh
    environment:
      MYSQL_DATABASE: demox_db
      MYSQL_USER: demox_user
      MYSQL_PASSWORD: demox-p4sswd
      MYSQL_ROOT_PASSWORD: testing